global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']
        labels:
          alias: 'mongos-router'
          cluster: 'mongo-cluster'
  - job_name: 'synthetic_tests'
    scrape_interval: 5s
    static_configs:
      - targets: ['test-runner:8001']